- x/docs/internal/types/keys.go
- x/id/internal/types/keys.go
- x/id/internal/types/msgs_test.go
> modules name review

- x/docs/internal/types/codec.go
- x/id/internal/types/codec.go
- x/id/internal/types/msgs_test.go
> Messages names review

- go.mod
- x/docs/alias.go
- x/docs/handler_test.go
- x/docs/internal/keeper/keeper_test.go
- x/docs/internal/keeper/querier_test.go
- x/docs/internal/keeper/test_commons.go
- x/government/internal/keeper/keeper_test.go
- x/government/internal/keeper/querier.go
- x/government/internal/keeper/querier_test.go
- x/government/internal/keeper/test_commons.go
- x/id/alias.go
- x/id/handler_test.go
- x/id/internal/keeper/keeper_test.go
- x/id/internal/keeper/querier_test.go
- x/id/internal/keeper/test_commons.go
- x/memberships/alias.go
- x/memberships/handler_test.go
- x/memberships/internal/keeper/keeper_test.go
- x/memberships/internal/keeper/querier_test.go
- x/memberships/internal/keeper/test_commons.go
Reviewed all modules' tests in order to delete setup test singleton
> Singleton removal from tests

- .circleci/config.yml
Closes #53 
______
For Admin Use:
> Updated CircleCI to Golang 1.13

- x/id/internal/keeper/keeper.go
This PR solves the nil pointer dereference detailed in #61, reviewers please make sure this change is okay before merging!
---
______
For Admin Use:
> Solve nil pointer dereference in id keeper

- x/docs/internal/types/document.go
This closes #65.
______
For Admin Use:
> Do not validate content_uri

- go.mod
- go.sum
This PR should fix the btcd-related issues we're having, including all the due mod updates.
After merging this in version/1.3.2 we should not have any more mod-related issues.
---
______
For Admin Use:
> Fix btcd retag issue

- go.mod
- go.sum
Please test these changes on your devbox before merging.
Steps to test:
- clone this branch
- `make build`
__No errors should appear__, but please report back if anything goes wrong!
______
For Admin Use:
> Fix go.{mod, sum} again, this time for master

- x/id/internal/types/common.go
- x/id/internal/types/common_test.go
- x/id/internal/types/did_deposit_request.go
- x/id/internal/types/msgs.go
- x/id/internal/types/msgs_test.go
- x/id/internal/types/proof.go
- x/id/internal/types/proof_test.go
- x/id/internal/types/pub_key.go
- x/id/internal/types/pub_key_test.go
- x/id/internal/types/request_status.go
- x/id/internal/types/request_status_test.go
- x/id/internal/types/service.go
- x/id/internal/types/service_test.go
Added some tests to the `id` module, working towards #52 
______
For Admin Use:
> Id module tests

- docs/x/id/query/read-identity.md
- x/docs/internal/keeper/keeper.go
- x/memberships/internal/keeper/alias_function.go
- x/memberships/internal/keeper/commons_test.go
- x/memberships/internal/keeper/handler.go
- x/memberships/internal/keeper/handler_test.go
- x/memberships/internal/keeper/keeper.go
- x/memberships/internal/keeper/keeper_credentials.go
- x/memberships/internal/keeper/keeper_credentials_test.go
- x/memberships/internal/keeper/keeper_invites.go
- x/memberships/internal/keeper/keeper_invites_test.go
- x/memberships/internal/keeper/keeper_rewards.go
- x/memberships/internal/keeper/keeper_rewards_test.go
- x/memberships/internal/keeper/keeper_test.go
- x/memberships/internal/keeper/keeper_tsp.go
- x/memberships/internal/keeper/keeper_tsp_test.go
- x/memberships/internal/keeper/querier.go
- x/memberships/internal/keeper/querier_test.go
- x/memberships/internal/types/credential.go
- x/memberships/internal/types/credential_test.go
- x/memberships/internal/types/invite.go
- x/memberships/internal/types/invite_test.go
- x/memberships/internal/types/membership.go
- x/memberships/internal/types/membership_test.go
- x/memberships/internal/types/msgs.go
- x/memberships/internal/types/msgs_test.go
- x/pricefeed/internal/keeper/keeper.go
Added tests for the `memberships` module. Works towards #52, #70 
______
For Admin Use:
> Memberships test

- docs/x/memberships/query/current-membership.md
- x/memberships/client/cli/query.go
- x/memberships/module.go
This PR adds query commands for the Memberships module.
______
For Admin Use:
> Memberships CLI query commands

- docs/x/government/README.md
- x/government/client/cli/query.go
- x/government/client/rest/query.go
- x/government/internal/keeper/querier.go
- x/government/module.go
- x/vbr/client/cli/query.go
This PR adds a CLI and a REST interface to easily retrieve the government address.
______
For Admin Use:
> Add REST/CLI interfaces to government

- docs/.vuepress/config.js
- docs/app_developers/README.md
- docs/nodes/validator-node-installation-mainnet.md
This PR add documentation about developers.
---
______
For Admin Use:
> Documentation improvement

- x/vbr/client/cli/query.go
- x/vbr/client/rest/query.go
- x/vbr/module.go
This PR adds the ability to query the VBR module via REST requests.
______
For Admin Use:
> VBR REST query client

- app/app.go
- x/vbr/genesis.go
- x/vbr/internal/keeper/handler.go
- x/vbr/internal/keeper/handler_test.go
- x/vbr/internal/keeper/keeper.go
- x/vbr/internal/keeper/keeper_test.go
- x/vbr/internal/keeper/querier_test.go
- x/vbr/internal/keeper/test_commons.go
- x/vbr/module.go
This PR fixes the logic behind vbr pool distributions, using x/supply `ModuleAccount` instead of a custom-built system.
______
For Admin Use:
- [ x Reviewers Assigned
> Distribute vbr pool accurately

- x/id/genesis.go
- x/id/internal/keeper/handler.go
- x/id/internal/keeper/handler_test.go
- x/id/internal/keeper/keeper.go
- x/id/internal/keeper/keeper_test.go
- x/id/internal/keeper/querier.go
- x/id/internal/keeper/querier_test.go
- x/id/internal/keeper/store_gen_key.go
- x/id/internal/keeper/store_gen_key_test.go
- x/id/internal/keeper/test_commons.go
- x/id/internal/types/keys.go
This PR removes any occurrence of AppendIfMissing from the id module.
---
______
For Admin Use:
> Remove AppendIfMissing from id

- x/commerciomint/internal/keeper/invariants.go
- x/memberships/internal/keeper/handler_test.go
- x/pricefeed/genesis.go
> Cmint invariant heightzero

- .circleci/config.yml
- go.mod
- go.sum
> save resources, avoid run tests twice

- app/app.go
- x/commerciomint/internal/keeper/handler_test.go
- x/commerciomint/internal/keeper/keeper.go
- x/commerciomint/internal/keeper/test_commons.go
- x/creditrisk/client/cli/query.go
- x/creditrisk/client/rest/query.go
- x/creditrisk/codec.go
- x/creditrisk/genesis.go
- x/creditrisk/genesis_test.go
- x/creditrisk/keeper.go
- x/creditrisk/module.go
- x/creditrisk/module_test.go
- x/creditrisk/querier.go
- x/creditrisk/querier_test.go
- x/creditrisk/types/types.go
- x/memberships/internal/keeper/handler_test.go
- x/memberships/internal/keeper/keeper.go
> new module: creditrisk

- x/creditrisk/client/cli/query.go
> creditrisk/client/cli: fix unmarshalling issue

- go.sum
- x/commerciomint/keeper/handler_test.go
- x/commerciomint/keeper/keeper.go
- x/commerciomint/keeper/keeper_test.go
- x/commerciomint/keeper/test_commons.go
- x/commerciomint/module.go
> x/commerciomint: autoliquidate implementation

- x/pricefeed/client/cli/tx.go
> Fix price feed command flags

- Makefile
- cmd/cnd/main.go
- cmd/cnd/testnet.go
- contrib/localnet/Makefile
- contrib/localnet/cndnode/Dockerfile
- contrib/localnet/cndnode/wrapper.sh
- docker-compose.yml
> port testnet command from gaia

- x/id/client/cli/tx.go
This PR implement base64 encoding for the ddo proof, and sets VerificationMethod field to the correct value, the bech32 pubkey of from address.
______
For Admin Use:
> Fixed DDO creation CLI command

- x/memberships/client/rest/query.go
> Query membership for user via REST

- docs/nodes/full-node-installation.md
- docs/nodes/hardware-requirements.md
- docs/nodes/validator-node-installation.md
> Validator node docs update

- go.mod
- go.sum
> use our tendermint fork

- cmd/cncli/main.go
> add missing commands

- docs/x/docs/README.md
- docs/x/id/README.md
> Docs update

- docs/x/docs/README.md
- docs/x/id/README.md
> Update shareDoc documentation

- go.mod
- go.sum
> upgrade to cosmos-sdk v0.38.4

- docs/x/commerciomint/README.md
- x/ante/ante.go
> Allow a maximum of 1 openCdp message for each transaction

- x/id/types/did_document.go
- x/id/types/did_document_test.go
- x/id/types/pub_key.go
This PR adds an hard requirement on DDO public keys: each one must be unique, PEM-wise.
______
For Admin Use:
> Require that each DDO public key is unique

- x/docs/internal/keeper/keeper_test.go
> Refactor testing style for x/docs/internal/keeper/keeper_test.go TestKeeper_ShareDocument

- x/docs/internal/keeper/keeper_test.go
> Refactor testing style for x/docs/internal/keeper/keeper_test.go TestKeeper_SaveDocumentReceipt

- x/docs/internal/keeper/keeper_test.go
> Refactor testing style for x/docs/internal/keeper/keeper_test.go TestKeeper_AddSupportedMetadataScheme

- x/docs/internal/keeper/keeper_test.go
> Refactor testing style for x/docs/internal/keeper/keeper_test.go TestKeeper_IsMetadataSchemeTypeSupported

- x/docs/internal/keeper/keeper_test.go
> Refactor testing style for x/docs/internal/keeper/keeper_test.go TestKeeper_TrustedSchemaProposersIterator

- x/docs/internal/keeper/keeper_test.go
> Refactor testing style for x/docs/internal/keeper/keeper_test.go TestKeeper_GetDocumentById

- x/docs/internal/keeper/keeper_test.go
> Refactor testing style for x/docs/internal/keeper/keeper_test.go TestKeeper_UserReceivedReceiptsIterator

- x/docs/internal/keeper/keeper_test.go
> Refactor testing style for x/docs/internal/keeper/keeper_test.go TestKeeper_SupportedMetadataSchemesIterator

- x/docs/internal/keeper/keeper_test.go
> Refactor testing style for x/docs/internal/keeper/keeper_test.go TestKeeper_UserSentDocumentsIterator

- x/docs/internal/keeper/keeper_test.go
> Refactor testing style for x/docs/internal/keeper/keeper_test.go TestKeeper_DocumentsIterator

- x/docs/internal/keeper/keeper_test.go
> Refactor testing style for x/docs/internal/keeper/keeper_test.go TestKeeper_IsTrustedSchemaProposer

- x/docs/internal/keeper/keeper_test.go
> Refactor testing style for x/docs/internal/keeper/keeper_test.go TestKeeper_AddTrustedSchemaProposer

- x/docs/internal/keeper/keeper_test.go
> Refactor testing style for x/docs/internal/keeper/keeper_test.go TestKeeper_UserReceivedDocumentsIterator

- x/docs/internal/keeper/keeper_test.go
> Add/refactor tests for x/docs

- x/docs/internal/types/document.go
- x/docs/internal/types/document_test.go
- x/id/types/did_document.go
- x/id/types/did_document_test.go
> Add length limits on some MsgShareDocument and MsgSetIdentity

- package-lock.json
- package.json
> Update node security

- go.mod
- go.sum
> upgrade to sdk v0.39.2 final

- cmd/cnd/testnet.go
- x/ante/ante.go
- x/ante/ante_test.go
- x/commerciokyc/client/cli/query.go
- x/commerciomint/client/cli/tx.go
- x/commerciomint/genesis.go
- x/commerciomint/genesis_test.go
- x/commerciomint/module_test.go
> Fix conversione rate handle

- x/vbr/keeper/keeper.go
- x/vbr/keeper/test_commons.go
- x/vbr/types/keys.go
> little fix

- x/did/client/cli/txSetIdentity.go
- x/did/legacy/v3.0.0/migrate_test.go
______
For Admin Use:
Closes #279
> Fix CLI set-identity in did module 

- x/vbr/keeper/keeper.go
- x/vbr/keeper/msg_server_vbr.go
- x/vbr/types/keys.go
> Add epoch hour identifier

- x/documents/keeper/keeper.go
- x/documents/keeper/keeper_test.go
- x/documents/keeper/querier.go
- x/documents/keeper/querier_test.go
- x/documents/keeper/test_commons.go
- x/documents/legacy/v2.2.0/types.go
- x/documents/legacy/v3.0.0/migrate.go
- x/documents/legacy/v3.0.0/migrate_test.go
- x/documents/legacy/v3.0.0/types.go
- x/documents/types/document_encryption_data.go
- x/documents/types/document_encryption_data_test.go
- x/documents/types/document_encryption_key_test.go
- x/documents/types/document_receipt.go
- x/documents/types/types.go
> Tests for legacy package of documents module

- docs/nodes/validator-node-installation.md
> Fix get operator address

- x/commerciomint/client/cli/query_position.go
- x/commerciomint/client/rest/query.go
- x/commerciomint/keeper/commons_test.go
- x/commerciomint/keeper/msg_server_position_test.go
- x/commerciomint/keeper/position.go
- x/commerciomint/keeper/position_test.go
- x/commerciomint/legacy/v2.2.0/types.go
- x/commerciomint/legacy/v3.0.0/migrate_test.go
- x/commerciomint/types/msgs_test.go
- x/commerciomint/types/params.go
- x/commerciomint/types/position_test.go
> Add flags to command and remove duplicate denom

- x/government/spec/01_state.md
- x/government/spec/README.md
> Add government spec

- x/documents/client/cli/query.go
- x/documents/client/cli/queryDocument.go
- x/documents/client/cli/queryDocument_test.go
- x/documents/client/cli/queryReceipts.go
- x/documents/client/cli/queryReceipts_test.go
- x/documents/client/cli/query_test.go
- x/documents/client/cli/tx.go
- x/documents/client/cli/txDocument.go
- x/documents/client/cli/txDocument_test.go
- x/documents/genesis.go
- x/documents/keeper/document_receipt_test.go
- x/documents/keeper/grpc_query.go
- x/documents/keeper/grpc_query_test.go
- x/documents/keeper/querier.go
- x/documents/types/document.go
- x/documents/types/genesis_test.go
- x/documents/types/msgs_test.go
This PR contains new tests to improve the coverage of the module.
Also, it contains comments for improving the module. Instructions to apply the comments are expected from the review process.
> documents coverage and improvements

- x/documents/spec/01_state.md
- x/documents/spec/02_keepers.md
- x/documents/spec/03_messages.md
- x/documents/spec/04_events.md
- x/documents/spec/05_client.md
- x/documents/spec/README.md
* small improvements, added query for listing receipts for a certain document ID
* updated events
* Add state description
* Add cli section
* improved messages section
* improved state tracking and types
* improved messages
* using correct module name
______
For Admin Use:
> Documentation for `x/documents` (#330)

- docs/.vuepress/config.js
- package-lock.json
- package.json
- x/did/spec/04_events.md
- x/vbr/spec/README.md
- yarn.lock
> Update npm deps

- x/vbr/keeper/grpc_query_test.go
- x/vbr/keeper/keeper_test.go
- x/vbr/keeper/msg_server_vbr.go
- x/vbr/keeper/msg_server_vbr_test.go
- x/vbr/keeper/querier_test.go
- x/vbr/legacy/v3.0.0/migrate.go
- x/vbr/legacy/v3.0.0/migrate_test.go
- x/vbr/types/genesis.go
- x/vbr/types/genesis_test.go
- x/vbr/types/msgs.go
- x/vbr/types/params.go
- x/vbr/types/params_test.go
Fixes #343 
In addition to the requested bug fix, the validation has been modified to avoid duplicate code
> allow EpochHour and use the same validation function

- x/commerciokyc/client/cli/tx.go
- x/commerciokyc/client/cli/tx_government.go
> Add kyc deposit command

- x/documents/types/document_receipt.go
- x/documents/types/document_receipt_test.go
- x/documents/types/test_common.go
> DocumentReceipt optional proof

- go.mod
- go.sum
- x/commerciokyc/client/cli/tx.go
- x/commerciokyc/client/cli/tx_government.go
- x/commerciokyc/spec/04_client.md
- x/documents/types/document_receipt.go
- x/documents/types/document_receipt_test.go
- x/documents/types/test_common.go
- x/vbr/keeper/grpc_query_test.go
- x/vbr/keeper/keeper_test.go
- x/vbr/keeper/msg_server_vbr.go
- x/vbr/keeper/msg_server_vbr_test.go
- x/vbr/keeper/querier_test.go
- x/vbr/legacy/v3.0.0/migrate.go
- x/vbr/legacy/v3.0.0/migrate_test.go
- x/vbr/types/genesis.go
- x/vbr/types/genesis_test.go
- x/vbr/types/msgs.go
- x/vbr/types/params.go
- x/vbr/types/params_test.go
> Update for v3.0.2

- x/commerciokyc/types/genesis.go
- x/commerciokyc/types/membership.go
- x/commerciokyc/types/membership_test.go
- x/commerciomint/genesis.go
- x/commerciomint/genesis_test.go
- x/commerciomint/types/genesis.go
- x/commerciomint/types/genesis_test.go
- x/commerciomint/types/msgs.go
- x/commerciomint/types/msgs_test.go
- x/commerciomint/types/position.go
- x/commerciomint/types/position_test.go
- x/documents/keeper/document_receipt.go
- x/documents/keeper/document_receipt_test.go
- x/epochs/abci_test.go
- x/government/genesis.go
- x/government/types/genesis.go
- x/vbr/genesis.go
- x/vbr/keeper/grpc_query_test.go
- x/vbr/keeper/keeper.go
- x/vbr/keeper/keeper_test.go
- x/vbr/keeper/msg_server_vbr.go
- x/vbr/keeper/msg_server_vbr_test.go
- x/vbr/keeper/params.go
- x/vbr/keeper/querier_test.go
- x/vbr/types/genesis.go
- x/vbr/types/genesis_test.go
- x/vbr/types/params.go
> Additional validation in types and keeper packages of some modules

- README.md
- docs/nodes/validator-node-handling.md
> Add move node documentation

- x/ante/ante.go
- x/ante/ante_test.go
> Add wasm store fees

- x/commerciokyc/keeper/grpc_query_invite.go
- x/commerciokyc/keeper/membership.go
- x/commerciokyc/keeper/querier.go
- x/commerciokyc/spec/README.md
> Fix commerciokyc docs

- docs/app_developers/commercioapi-sharedoc.md
- docs/docs2.2.0/app_developers/commercioapi-sharedoc.md
doc_storage_uri field deleted
internal ref: [#54](https://scw-gitlab.zotsell.com/Commercio/Server/api-services/-/issues/54)
> documentation update

- docs/.vuepress/config.js
- docs/nodes/validator-node-handling.md
- package-lock.json
- yarn.lock
> Add keybase identity

- docs/nodes/validator-node-update.md
> Update validator instructions

- docs/nodes/full-node-installation.md
> Add fix cosmovisor docs

- CHANGELOG.md
- README.md
> Add 4.1.0 to changelog

- Dockerfile.staticlink
- app/app.go
- app/ibc_portname_generator.go
- config.yml
- go.mod
- go.sum
- testutil/simapp/simapp.go
- x/ante/ante.go
- x/ante/ante_test.go
* New Dockerfile
* Fix wasmd ibc bug adding ibc port customization function Hex IBC port conversion
* Updated go.mod
* Add wasm decorator to ante
* Add gas meter
* Fix update-instantiate-config wasmd issue
* Add update handler
* Removed comment
* Revert docker file
______
For Admin Use:
> Marco/main 5.1.0/add update (#412)

- docs/.vuepress/config.js
- docs/nodes/full-node-installation.md
- docs/nodes/statesync-node-quicksync.md
- docs/nodes/validator-node-handling.md
- docs/nodes/validator-node-installation.md
- package-lock.json
- yarn.lock
> Documentation update 5.1.0

- x/vbr/keeper/hooks.go
> Fix don't panic if var pool is empty
